/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconCarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    'IconFluentEmoji:clownFace': typeof import('~icons/fluent-emoji/clown-face')['default']
    'IconFluentEmojiHighContrast:clownFace': typeof import('~icons/fluent-emoji-high-contrast/clown-face')['default']
    'IconGameIcons:clown': typeof import('~icons/game-icons/clown')['default']
    'IconMaterialSymbols:5gMobiledataBadgeRounded': typeof import('~icons/material-symbols/5g-mobiledata-badge-rounded')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
